try {
  let x = y + 1;
} catch (err) {
  console.log(err);
}
